### ISSUE TITLE
При создании бэкапа на удаленном сервере разносить бэкапы сайтов по пользователям

### ISSUE THREAD

**Issue by cave2006** [Delo-Design/rish#11]
Сейчас на удаленном сервере создаются бэкапы по следующему пути: /date/
Это нормально, если на сервере только один пользователь.
Предлагаю создавать бэкапы по пути: /user/date/
Это облегчит предоставление доступа конечному пользователю на уровне облака

**Comment by progreccor** [comment]
да разумно

**Comment by progreccor** [comment]
не прошло и два года...
