### ISSUE TITLE
upload_tmp_dir для каждого пользователя

### ISSUE THREAD

**Issue by kernusr** [Delo-Design/rish#19]
При использовании Joomla + rish стало надоедать предупреждение "В конфигурации PHP не определен каталог временных файлов"

![изображение](https://github.com/user-attachments/assets/d64aa382-2173-4300-80ad-cf3c3e9f8404)

Собственно, проблема в том, что у php явно не задан путь для `upload_tmp_dir`

Предлагаю, на ровне с созданием папок пользователя https://github.com/Delo-Design/rish/blob/1cfe473d68869e827d66305c927db0be771c7243/ri.sh#L326-L328

1. создавать папку 

```shell
mkdir /var/www/${NAME}/tmp
```

2. настраивать её владельца

```shell
chown ${NAME}:${NAME} /var/www/${NAME}/tmp
```

3. прописывать её в конфигурационный файл пулла php-fpm, при создании сайта https://github.com/Delo-Design/rish/blob/1cfe473d68869e827d66305c927db0be771c7243/create_site.sh#L160-L161

```shell
echo "php_value[upload_tmp_dir] = /var/www/${username}/tmp"
```

**Comment by progreccor** [comment]
Добавлено в версии 2.1.1
Так же добавлено обновление всех существующих уже пулов до этой функции
